### ISSUE TITLE
Adicionar sugestões no campo "Título" ao adicionar sessões

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#29]
Ao cadastrar uma sessão manualmente, o campo título é usado pra conectar a sessão com os filmes.

Enquanto o usuário digita o nome do filme, seria legal ter uma dropdown mostrando filmes com nomes parecidos que já existem no sistema.

Isso vai facilitar o cadastro e diminuir a quantidade de filmes duplicados.

![Screenshot 2024-04-08 at 17 28 07](https://github.com/guites/cinemaempoa/assets/71985299/269aedcd-bef0-4a54-ae47-11c10c85baef)

**Comment by guilhermesrc** [comment]
posso assumir essa issue!

**Comment by guites** [comment]
Claro!! Qualquer dúvida é só falar

**Comment by guites** [comment]
Fechado pelo PR #50
