### ISSUE TITLE
Opção de descartar sessões criadas por importação

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#30]
às vezes, ao importar um arquivo .json, vem uns filmes cagados devido à problemas no scrapper.

Seria bom ter um botão pra rapidamente excluir sessões que deram errado, assim como temos hoje um botão pra rapidamente aprovar sessões importadas corretamente.

![Screenshot 2024-04-08 at 17 32 40](https://github.com/guites/cinemaempoa/assets/71985299/24457033-a636-41c4-989d-cb0cf4c1bd9d)

**Comment by guilhermesrc** [comment]
posso fazer essa?

**Comment by guites** [comment]
Claro! Qualquer dúvida que surgir é só perguntar.

**Comment by guilhermesrc** [comment]
o botão é pra sempre estar disponível ou somente em filmes que ainda estão no estado de rascunho?

**Comment by guites** [comment]
Eu tinha pensado em aparecer apenas para os `screenings` que estão com o `draft = True` (https://github.com/guites/cinemaempoa/blob/implement-flask-backend/flask_backend/models.py#L46).

Essa demanda surgiu porque às vezes o scrapper pega o título dos filmes com erro, por exemplo: 

![Captura de Tela 2024-04-24 às 17 53 56](https://github.com/guites/cinemaempoa/assets/71985299/4145b89a-1289-4509-99d1-8953fca1b8fd)

Nesse exemplo, em um outro dia eu já deletei essa `screening` que o filme é `16hLANTERNA DE LÓTUS`, mas como eu ainda não corrigi o scrapper, ele vai sempre criar uma screening pra esse cara.

O fluxo seria (pode ignorar se não fizer sentido, tá meio complicado mesmo):

1. Importei o arquivo .json
2. Vi que foi criado um filme com o nome errado (16hLANTERNA DE LÓTUS), e gerada uma screening desse filme pro "Sala da Redenção".
3. Editei essa screening e corrigi o nome do filme (isso resulta na criação de outro filme, de nome `LANTERNA DE LÓTUS` no banco de dados), e também coloquei uma foto.
4. No outro dia, eu rodo os scrappers e importo um novo json. Nesse json vem novamente o filme com o nome errado.
5. É criada uma sessão do filme com o nome errado (16hLANTERNA DE LÓTUS) na "Sala da Redenção".
6. Se eu editar esse screening errado e corrigir o nome dela, nós vamos ficar com duas screenings do mesmo filme no mesmo cinema...

(você pode reproduzir esses passos com esse arquivo json aqui: [18-04-2024-import.json](https://github.com/guites/cinemaempoa/files/15100257/18-04-2024-import.json))

![Captura de Tela 2024-04-24 às 18 02 31](https://github.com/guites/cinemaempoa/assets/71985299/7e460b49-ac99-4686-8784-99f53ad6b82e)

Então eu pensei que a solução mais fácil seria poder descartar (excluir) essa sessão errada, enquanto ela ainda está em rascunho (draft).

Mas eu estou aberto à quaisquer sugestões de como lidar com esse problema!

**Comment by guites** [comment]
Implementado no PR #57
