### ISSUE TITLE
Rodar scrappers direto da tela de importação

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#31]
Atualmente o usuário precisa rodar os scrappers pelo terminal,com o comando

```bash
./cinemaempoa.py -r capitolio sala-redencao cinebancarios paulo-amorim > import.json
```

pra depois acessar a tela de "Importar sessões" e selecionar o arquivo json do seu computador.

Seria legal ter também uma opção "Rodar importação" ou algo do tipo, que fizesse esse trabalho automaticamente.

**Comment by fbgrigolo** [comment]
Assumindo essa tarefa

**Comment by guites** [comment]
Eu vou deixar aqui algumas explicações sobre como eu imagino que essa feature deva ser implementada.

Quando o script de scrapping é rodado, a lógica referente por raspar os sites e gerar o arquivo json fica em `cinemaempoa.py` (<https://github.com/guites/cinemaempoa/blob/implement-flask-backend/cinemaempoa.py#L70>)

basicamente nós criamos uma lista 

```python
 features = []
```

e pra cada sala de cinema, instanciamos uma classe específica dos scrappers.

Um detalhe é que todas as classes de scrapping tem um mesmo método, responsável por raspar o seu respectivo site: `get_daily_features_json()`

```python
# raspagem do site do capitólio
feature = {
    "url": "http://www.capitolio.org.br",
    "cinema": "Cinemateca Capitólio",
    "slug": "capitolio",
}
cap = Capitolio()
feature["features"] = cap.get_daily_features_json()
features.append(feature)

# raspagem do site do paulo amorim
feature = {
    "url": "https://www.cinematecapauloamorim.com.br",
    "cinema": "Cinemateca Paulo Amorim",
    "slug": "paulo-amorim",
}
pauloAmorim = CinematecaPauloAmorim()
feature["features"] = pauloAmorim.get_daily_features_json()
features.append(feature)
```

e assim por diante. No fim, temos essa lista `features`, que é salva em um arquivo .json

O ideal é que tenhamos um endpoint específico pra rodar essa lógica de chamar as classes de scrapping e preparar a lista com todos os resultados.

Por exemplo (baseado no PR #46):

```
# lá em flask_backend/routes/screening.py

@bp.route("/screening/scrap", methods=["POST"])
@login_required
def runScrap():
    if request.method == "POST":
        # chamar lógica de instanciar os scrappers
        # raspagem do site do capitólio
        feature = {
            "url": "http://www.capitolio.org.br",
            "cinema": "Cinemateca Capitólio",
            "slug": "capitolio",
        }
        cap = Capitolio()
        feature["features"] = cap.get_daily_features_json()
        features.append(feature)
        
        # raspagem do site do paulo amorim
        feature = {
            "url": "https://www.cinematecapauloamorim.com.br",
            "cinema": "Cinemateca Paulo Amorim",
            "slug": "paulo-amorim",
        }
        pauloAmorim = CinematecaPauloAmorim()
        feature["features"] = pauloAmorim.get_daily_features_json()
        features.append(feature)
        ... # assim por diante
```
