### ISSUE TITLE
Validar tamanho das imagens na criação de sessões

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#34]
Ao criar sessões individuais, uma imagem muito grande vai cair num erro de "entity too large" (ex. uma imagem de 9mb).

Tela: http://127.0.0.1:5000/screening/new

Precisamos validar o tamanho da imagem no frontend, pro usuário não descobrir só depois de clicar em enviar.

O ideal é mostrar um aviso embaixo do seletor de arquivos do tipo "tamanho máximo da imagem: 500kb", e dar algum feedback caso ele selecionar um arquivo muito grande.

**Comment by fbgrigolo** [comment]
Assumindo essa issue
