### ISSUE TITLE
Validar formatação de código nos PRs

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#36]
Seria legal termos uma forma de só permitir pull requests formatados com o [black](https://github.com/psf/black) e [isort](https://pypi.org/project/isort/).

Precisamos também definir um formatador padrão pros templates (arquivos .html).

Isso vai facilitar muito entender o que é alteração no código e o que é alteração de formatação devido aos editores dos devs.

Se não der pra fazer isso via github, uma alternativa é criar um conjunto de pre-commit hooks pro projeto, e pedir pra todos utilizarem antes de abrir PRs : <https://pre-commit.com/>.

**Comment by vianaz** [comment]
@guites posso pegar essa issue?

**Comment by guites** [comment]
Claro!! Qualquer problema pode enviar por aqui
