### ISSUE TITLE
Hospedar imagens em um servidor externo no ambiente de produção

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#43]
O deploy é feito via fly.io, o que significa que quando o container é desligado (ele desliga automaticamente após alguns minutos sem acessos), todos os arquivos subidos (.jsons e imagens) são deletados. Daí acaba acontecendo isso:

![Screenshot 2024-04-10 at 19 38 20](https://github.com/guites/cinemaempoa/assets/71985299/c7d92617-23aa-4a1d-921f-e99d17ee3ca8)

Uma alternativa é subir as imagens num servidor separado. Existem APIs gratuitas como a https://apidocs.imgur.com/ que integram facilmente com código Python.

Idealmente nós manteriamos o upload "local" no ambiente de desenvolvimento, e usariamos a API externa no ambiente de produção. Assim quem for rodar o projeto não precisa passar pelo processo de gerar uma chave de API, etc.

**Comment by guites** [comment]
Este repositório tem um exemplo de integração com a API do imgur (em node.js) que pode ser adaptado: https://github.com/gchan-board/gchan-backend/blob/open-api-documentation/db/imgur.js

**Comment by D3C0RU5** [comment]
I'll take it to correct it ;)

**Comment by guites** [comment]
Thanks! If you have any questions, please let me know.

**Comment by D3C0RU5** [comment]
@guites check my solution
https://github.com/guites/cinemaempoa/pull/55

**Comment by guites** [comment]
Closed by #55 (sorry I stole your contribution)
