### ISSUE TITLE
Erro de timezone devido ao uso de sqlite

### ISSUE THREAD

**Issue by guites** [guites/cinemaempoa#45]
As requisições no banco estão sofrendo um desvio de 3h devido à timezone padrão do banco.

Por causa disso, as 21h os filmes do dia atual param de aparecer na página.

![Screenshot 2024-04-10 at 21 19 25](https://github.com/guites/cinemaempoa/assets/71985299/04a776e3-6720-4eb4-9982-749921d47273)

Caso não der pra mexer na timezone do banco, ou alterar as queries seja muito complicado, o ideal seria, a partir do momento que não temos mais sessões do dia atual, passar as mostrar as sessões do próximo.

**Comment by enieber** [comment]
Parece algo que eu consiga resolver.. vou verificar como posso ajudar

**Comment by enieber** [comment]
Pelo que pude pesquisar o [sqlite não tem um timezone](https://stackoverflow.com/questions/37619526/how-can-i-change-the-default-sqlite-timezone) o que está acontecendo é que o timezone do servidor é UTC que é 3 horas adiantado do horario de POA.

Tem duas formas de corrigir o problema:

- modificar o timezone do servidor para -3
- fazer uma verificação com base no timezone -3, [aqui tem um exemplo](https://www.alura.com.br/artigos/lidando-com-datas-e-horarios-no-python) usando as dependencias do python ou uma lib

Tentei fazer a segunda opção, mas fiquei confuso como poderia fazer isso sem quebrar nada que já está funcionando então fica minha recomendação de caso queira seguir pela segunda opção, alterar o ``  repository/screenings.py``    em todos os lugares que faz o uso de data.

**Comment by guites** [comment]
Opa, valeu pela dica. Dando uma olhada aqui, o fly.io [permite alterar a tz do servidor](https://community.fly.io/t/app-is-using-wrong-timesone/11517/4).

O query afetado em questão é esse:

```python
def get_days_screenings_by_cinema_id(
    cinema_id: int, day: date
) -> Tuple[ScreeningDate, str]:
    screening_dates = (
        db_session.query(Screening)
        .join(ScreeningDate)
        .filter(Screening.cinema_id == cinema_id)
        .filter(func.date(ScreeningDate.date) == day)
        .all()
    )

    return screening_dates
```

então eu tô pegando o campo `date` da tabela `screening_dates`, que é assim:

```
sqlite> select * from screening_dates;
1|1|2024-04-10|15:00
2|2|2024-04-10|17:00
3|3|2024-04-10|19:00
9|9|2024-04-10|14:15
```

e comparando com essa variável `day`, que eu passo como argumento. Lá no endpoint, é feito o seguinte

```python
today = date.today()
screenings: List[Screening] = get_days_screenings_by_cinema_id(cinema.id, today)
```

então parece que a melhor solução é mudar a TZ do servidor pra America/Sao_Paulo, daí o `date.today()` vai retornar o dia certo dentro do nosso fuzo.. ao menos em teoria.

Se for isso, me parece que não vai ser preciso mudar os queries.

Muito obrigado pelo direcionamento!

**Comment by guites** [comment]
Validado agora que tá funcionando! Fechando aqui.

![Screenshot 2024-04-11 at 21 23 11](https://github.com/guites/cinemaempoa/assets/71985299/1500d9bb-ec70-4b46-bd07-6716903f64c9)
